name: Update submodules
on:
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
jobs:
  update_submodules:
    name: Update submodules
    runs-on: ubuntu-latest
    env:
      TZ: "Asia/Tokyo"
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          # This token is required to allow checkout of private submodules.
          # It provides access to the repositories referenced as submodules in this repository.
          token: ${{ secrets.NARD_TEX_PACKAGES_TOKEN }}

      - name: Update submodules
        run: |
          git submodule update --remote --recursive || { echo "Submodule update failed"; exit 1; }

      - name: Set Git status
        id: set-git-status
        run: echo "CHANGED=$(git status --porcelain | grep -q . && echo 'true' || echo 'false')" >> $GITHUB_OUTPUT

      - name: Get current datetime
        id: set-datetime
        run: |
          echo "CURRENT_TIME=$(date '+%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT

      - name: Set branch name
        id: set-branch-name
        env:
          CURRENT_TIME: ${{ steps.set-datetime.outputs.CURRENT_TIME }}
        run: |
          echo "BRANCH_NAME=update-github-submodules-$CURRENT_TIME" >> $GITHUB_OUTPUT
      - name: Check GitHub output
        id: check-github-output
        env:
          CHANGED: ${{ steps.set-git-status.outputs.CHANGED }}
          CURRENT_TIME: ${{ steps.set-datetime.outputs.CURRENT_TIME }}
          BRANCH_NAME: ${{ steps.set-branch-name.outputs.BRANCH_NAME }}
        run: |
          echo CHANGED: $CHANGED
          echo CURRENT_TIME: $CURRENT_TIME
          echo BRANCH_NAME: $BRANCH_NAME

      - name: Commit changes
        if: steps.set-git-status.outputs.CHANGED == 'true'
        env:
          CURRENT_TIME: ${{ steps.set-datetime.outputs.CURRENT_TIME }}
          BRANCH_NAME: ${{ steps.set-branch-name.outputs.BRANCH_NAME }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout -b $BRANCH_NAME
          git add .
          git commit -m "Update submodules at $CURRENT_TIME"

      - name: Push branch
        if: steps.set-git-status.outputs.CHANGED == 'true'
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.set-branch-name.outputs.BRANCH_NAME }}

      - name: Create Pull Request
        if: steps.set-git-status.outputs.CHANGED == 'true'
        run: |
          gh pr create -B main -t "Update submodules" -b "サブモジュールの自動更新"
        env:
          GH_TOKEN: ${{ secrets.NARD_TEX_PACKAGES_TOKEN }}
